name: Release

on:
  push:
    tags:
      - 'v*'

jobs: 
  release:
    permissions: 
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0

      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
      - uses: actions/setup-node@v4
        with:
            node-version: 20.x
            registry-url: 'https://registry.npmjs.org'
      
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun install
        shell: bash
      
      - name: Build
        run: bun run build

      - name: Check version
        id: check_version
        run: |
          version=$(node -p "require('./package.json').version")
          if [[ $version == *"beta"* ]]; then
            echo "::set-output name=IS_PRERELEASE::true"
          else
            echo "::set-output name=IS_PRERELEASE::false"
          fi
          
      - name: Publish to npm beta
        if: steps.check_version.outputs.IS_PRERELEASE == 'true'
        run: npm publish --access public --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Publish to npm
        if: steps.check_version.outputs.IS_PRERELEASE == 'false'
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}